# Generated by Django 3.1.7 on 2021-03-05 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendorid', models.FloatField()),
                ('tpep_pickup_datetime', models.DateTimeField()),
                ('trip_distance', models.FloatField()),
                ('payment_type', models.FloatField()),
            ],
        ),
    ]
