# Generated by Django 3.1.7 on 2021-03-06 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datatable_null_vendors', '0002_remove_datatable_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatable',
            name='payment_type',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='datatable',
            name='vendorid',
            field=models.FloatField(null=True),
        ),
    ]
