# Generated by Django 4.0.1 on 2022-01-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datatable_null_vendors', '0006_auto_20210306_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yellowtaxis',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('vendorid', models.FloatField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('tpep_pickup_datetime', models.DateTimeField(blank=True, null=True)),
                ('tpep_dropoff_datetime', models.DateTimeField(blank=True, null=True)),
                ('trip_duration_seconds', models.IntegerField(blank=True, null=True)),
                ('trip_duration', models.CharField(blank=True, max_length=5, null=True)),
                ('passenger_count', models.FloatField(blank=True, null=True)),
                ('trip_distance', models.FloatField(blank=True, null=True)),
                ('ratecodeid', models.FloatField(blank=True, null=True)),
                ('store_and_fwd_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('pulocationid', models.FloatField(blank=True, null=True)),
                ('dolocationid', models.FloatField(blank=True, null=True)),
                ('payment_type', models.FloatField(blank=True, null=True)),
                ('fare_amount', models.FloatField(blank=True, null=True)),
                ('extra', models.FloatField(blank=True, null=True)),
                ('mta_tax', models.FloatField(blank=True, null=True)),
                ('tip_amount', models.FloatField(blank=True, null=True)),
                ('tolls_amount', models.FloatField(blank=True, null=True)),
                ('improvement_surcharge', models.FloatField(blank=True, null=True)),
                ('total_amount', models.FloatField(blank=True, null=True)),
                ('congestion_surcharge', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelTable(
            name='datatable',
            table='yellowtaxis',
        ),
    ]
