# Generated by Django 4.0.1 on 2022-01-17 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datatable_null_vendors', '0007_yellowtaxis_alter_datatable_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='datatable',
            table=None,
        ),
        migrations.AlterModelTable(
            name='yellowtaxis',
            table='yellowtaxis',
        ),
    ]
